In [1]:
input_list = [5,6,4,8,9]
cube = list(map(lambda x: x**3, input_list))

In [2]:
print(cube)

[125, 216, 64, 512, 729]


In [7]:
input_str_list = ['San Jose', 'San Francisco', 'Santa Fe', 'Houston']
string_with_s = sum(map(lambda s: s[0].lower() == 's', input_str_list))

In [8]:
print(string_with_s)

3


In [9]:
input_names = [ ['Ankur', 'Avik', 'Kiran', 'Nitin'], ['Narang', 'Sarkar', 'R', 'Sareen']]

name = list(map(lambda x, y : x + " " + y, input_names[0], input_names[1]))

In [10]:
print(name)

['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']


In [13]:
list_answer = list(filter(lambda x: x % 5 == 0, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

print(list_answer)

[5, 10]


In [14]:
input_list = ['soap','sharp','shy','silent','ship','summer','sheep']
answer = list(filter(lambda x: x[0].lower() == 's' and x[-1].lower() == 'p', input_list))

answer

['soap', 'sharp', 'ship', 'sheep']

In [17]:
from functools import reduce

input_list = ['All','you','have','to','fear','is','fear','itself']
ans = reduce(lambda x, y: x + ' ' + y, input_list)

ans

'All you have to fear is fear itself'

In [24]:
input_list = [31, 63, 76, 89]
answer = reduce(lambda x, y: x if x > y else y, input_list)

answer

89

In [25]:
list_1 = [2,3,4,5]
list_2 = [7,8,9,6]

import numpy as np

array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = array_1 * array_2

print(list(array_3))

[14, 24, 36, 30]


In [27]:
array_multipleof5 = np.arange(5, 55, 5, dtype=int)

print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


In [31]:
n = int(input("Enter number"))
print(np.tile([0, 1], n))

Enter number2
[0 1 0 1]


In [33]:
array_1 = [1, 2, 3, 5, 4, 6, 7, 8, 5, 3, 2]
print(array_1[:3])

[1, 2, 3]


In [39]:
array = np.array([[5,6,7],[7,6,5],[0,8,7]])
print(array[:, 1])

[6 6 8]


In [42]:
array = [[11, 12, 13, 14],
 [21, 22, 23, 24],
 [31, 32, 33, 34]]

array = np.array(array)

col_first = array[:, 0] 
row_first = array[0, :]
col_last = array[:, -1]
row_last = array[-1, :]

print(col_first)
print(row_first)
print(col_last)
print(row_last)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]
