In [1]:
import numpy as np

In [31]:
v1 = np.array([3, 2])
b2 = np.array([[3, -3], [4, -5]])
b1 = np.array([[1, 0], [0, 1]])

In [32]:
m = np.matmul(np.linalg.inv(b2), b1)
m

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [33]:
v2 = np.matmul(m, v1)

In [34]:
v2

array([3., 2.])

Going from non-standard scaler to standard scaler

In [6]:
v1, v2 = v2, v1
b1, b2 = b2, b1

In [7]:
m = np.matmul(np.linalg.inv(b2), b1)
m

array([[1., 1.],
       [2., 3.]])

In [10]:
v2 = np.matmul(m, v1)

v2

array([4., 9.])