In [65]:
import numpy as np
from math import pi

In [66]:
a = [2, 1, 0, 0]
b = [1, 1, 1, 0]

a_dot_b = np.dot(a, b)
a_mag = np.linalg.norm(a)
b_mag = np.linalg.norm(b)

print('Angle b/w 1 & 4:', round(np.arccos(a_dot_b/(a_mag * b_mag)) * (180/pi), 2))

Angle b/w 1 & 4: 39.23


In [67]:
a = [1, 1, 0, 0]
b = [1, 1, 1, 0]


a_dot_b = np.dot(a, b)
a_mag = np.linalg.norm(a)
b_mag = np.linalg.norm(b)

print('Angle b/w 3 & 4:', round(np.arccos(a_dot_b/(a_mag * b_mag)) * (180/pi), 2))

Angle b/w 3 & 4: 35.26


In [68]:
a = [2, 1, 0, 0]
b = [1, 1, 0, 0]

a_dot_b = np.dot(a, b)
a_mag = np.linalg.norm(a)
b_mag = np.linalg.norm(b)

print('Angle b/w 1 & 3:', round(np.arccos(a_dot_b/(a_mag * b_mag)) * (180/pi), 2))

Angle b/w 1 & 3: 18.43


In [69]:
a = [2, 1, 0, 0]
b = [1, 1, 1, 0]

a_dot_b = np.dot(a, b)
a_mag = np.linalg.norm(a)
b_mag = np.linalg.norm(b)

print('Angle b/w 1 & 4:', round(np.arccos(a_dot_b/(a_mag * b_mag)) * (180/pi), 2))

Angle b/w 1 & 4: 39.23


In [70]:
a = np.array([[2, 7, 1], [-2, 1, 8], [3, 4, -2]])
b = np.array([[8, 1, 3], [3, 5, 8], [7, -2, -4]])

inverse = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [71]:
a

array([[ 2,  7,  1],
       [-2,  1,  8],
       [ 3,  4, -2]])

In [72]:
b

array([[ 8,  1,  3],
       [ 3,  5,  8],
       [ 7, -2, -4]])

In [73]:
np.matmul(a, b)

array([[ 44,  35,  58],
       [ 43, -13, -30],
       [ 22,  27,  49]])

In [74]:
c = np.linalg.inv(a)

c

array([[-0.55737705,  0.29508197,  0.90163934],
       [ 0.32786885, -0.1147541 , -0.29508197],
       [-0.18032787,  0.21311475,  0.26229508]])

In [75]:
d = np.linalg.inv(c)

d

array([[ 2.,  7.,  1.],
       [-2.,  1.,  8.],
       [ 3.,  4., -2.]])

In [76]:
m = np.array([[2, 1, 1], [3, 2, 1], [2, 1, 2]])

m_inv = np.linalg.inv(m)

m_inv

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])